all:
  children:
    oracle_servers:
      hosts:
        genx-db-711.genex.com:
          ansible_host: 192.168.10.71
        genx-db-712.genex.com:
          ansible_host: 192.168.10.72

  # ==========================================================================
  # GLOBAL VARIABLES
  # ==========================================================================
  vars:
    # Connection settings
    ansible_user: ansible
    ansible_ssh_private_key_file: /home/ansible/.ssh/id_ed25519
    ansible_become: true
    ansible_become_method: sudo
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

